[package]
name = "playdia"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Playdia standalone frontend (CLI + windowed player)"

[[bin]]
name = "playdia"
path = "src/main.rs"

[[bin]]
name = "playdia-emu"
path = "src/bin/playdia_emu.rs"

[dependencies]
playdia-core = { path = "../playdia-core" }
anyhow = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
minifb = { workspace = true }
rodio = { workspace = true }
