[package]
name = "playdiaemu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Playdia standalone emulator (window + CLI)"

[[bin]]
name = "playdia-emu"
path = "src/main.rs"

[dependencies]
playdiaemu-core = { path = "../playdiaemu-core" }
anyhow = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
minifb = { workspace = true }
rodio = { workspace = true }
image = { workspace = true }
gilrs = { workspace = true }
